### PR TITLE
Changed the ParkingLot solution to much simpler recursion solution

### PR DESCRIPTION
**Pull request by RedaFakih**
## Why?
- Was going through the repository and I found the ParkingLot solution alot more complicated than it should be so this is another proposed (simpler) solution using recursion.

Thanks. (Reda Fakih, s308192)

### CODE REVIEW

**Review by squillero — CHANGES_REQUESTED** [review]
Cool, nice ;-)

Two comments: (1) it doesn't work from a general, arbitrary situation, like "--*--------*-*-"; (2) can you provide a new file, and I'll add your solution to the repo. 

Thanks!

**Comment by RedaFakih** [comment]
Oh okay, about comment 1, I thought that we were supposed to start from an empty parking lot and not a one that may contain a car. Well in that case, my solution breaks, however an idea that comes from the top of my head is that we could divide the list if there are already some cars there, apply my solution to the divided lists then merge everything back together. Not sure if that works but sounds like a good idea. A new file is submitted!

**Comment by RedaFakih** [comment]
Im not sure if you added the correct file...

**Comment by squillero** [comment]
I added your file by hand because your commit still included changes to my code, that I’d rather not to include without a discussion…

Regards
gx

--
Giovanni Squillero | ***@***.***
Politecnico di Torino / DAUIN
https://staff.polito.it/giovanni.squillero/
~
I'll top the bill
I'll overkill
I have to find the will to carry on
On with the
On with the show
The show must go on
      — Queen, "The Show Must Go On", 1991

**Pull request closed without merging**
